server:
  error:
    include-exception: false
    include-stacktrace: never
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET}

cloud:
  access: ${S3_ACCESS_KEY}
  secret: ${S3_SECRET_KEY}
  aws:
    s3:
      bucket: triple
    region:
      static: ap-northeast-2
    stack:
      auto: false
---

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_URL}
    username: ${PROD_USERNAME}
    password: ${PROD_PASSWORD}

---

spring:
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TEST_URL}
    username: ${TEST_USERNAME}
    password: ${TEST_PASSWORD}

---

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_URL}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}